language: node_js
notifications:
  email: false
branches:
  - production
  - staging
jobs:
  include:
    - stage: Testing
      name: Front-End Tests
      env: TARGET=packages/frontend
      script: .travis/tests.sh
    - name: Web App Tests
      env: TARGET=packages/web
      script: .travis/tests.sh
    - name: Mobile App Tests
      env: TARGET=packages/mobile
      script: .travis/tests.sh
    - stage: Building
      name: Front-End Build
      env: TARGET=packages/frontend
      script: .travis/build.sh
    - name: Web App Build
      env: TARGET=packages/web
      script: .travis/build.sh
    - stage: Deployment
      name: Dummy Deployment
      script: skip
      after_script: echo "Deployed!"