language: node_js
notifications:
  email: false
branches:
  - production
  - staging
jobs:
  include:
    - stage: Testing
      name: Front-End Tests
      env: TARGET=packages/frontend
      script: .travis/tests.sh
    - name: Dummy Tests
      script: echo "Hello world!"
    - stage: Deployment
      name: Dummy Deployment
      script: skip
      after_script: echo "Deployed!"