os: linux
dist: xenial
language: node_js
notifications:
  email: false
jobs:
  include:
  - stage: Testing
    name: Front-End Tests
    env: TARGET=packages/frontend
    script: ".travis/tests.sh"
  - name: Web App Tests
    env:
    - TARGET=packages/web
    - SKIP_PREFLIGHT_CHECK=true
    script: ".travis/tests.sh"
  - name: Mobile App Tests
    env: TARGET=packages/mobile
    script: ".travis/tests.sh"
  - stage: Building
    name: Front-End Build
    env: TARGET=packages/frontend
    script: ".travis/build.sh"
    workspaces:
      create:
        name: fe_build
        paths: .
  - name: Web App Build
    env: TARGET=packages/web
    script: ".travis/build.sh"
    workspaces:
      create:
        name: wa_build
        paths: .
  - stage: Deployment
    name: Front-End Deployment
    env:
      - TARGET=packages/frontend
      - BUCKET=s3://devshare-frontend
    workspaces:
      use: fe_build
    install: skip
    script: skip
    before_deploy: .travis/aws-setup.sh
    deploy:
      provider: script
      script: .travis/s3-deploy.sh
      skip_cleanup: true
      on:
        branch: production
    
env:
  global:
  - SKIP_PREFLIGHT_CHECK=true
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_DEFAULT_OUTPUT=json
  - secure: Nq6l5useI0kIrnh6kNUqCAAF65TOTk4dOQp8JY2sagUha1yMG8mnfkeKTVaCM6U7rhDeCChl9YpOrw8xdlz495TTcQQy2GEnVU81YOmPoZkQy4c79GHRf9pXXbhXNYtQnIQSuMbXBYyzyGF0FzbTeqsiIwXpEtCrhbYgdKsOXUit+EGaTaDy09mCHjD5KnBzvklRyJDqRaB13+baSsyEmSkimS+HpOKTHc3Rl5YlhA7kCsoNXE8rpGaVQUZHXaojZChLesqz9ojLXVOFr5QLuYx4PUxVzrHVNL49Xm4b0GYl1mYKatVC75XRlO3jhLfWnkPhYN0xjYexrjzHsJ9JoYn+Ey1/o0H778PIl9zque0zII2pxxgxJQ7z1ou3U/oK8BJb1DGzasH7/u1HFjYRJVL3tzXqk/XGVEtT+E00ByxonQjU2c194guxOCeZNZ3eiXG/RvE7r8kbrxfCUlh1jw0Y+N72v7SSDHC43bFESAleuUmKtAoECvxTtct+8AH+XJ0zeFLawiJLTlOBkNYNyT6gs8IuP+s56kjGyGJz+c65x6g2gOZ1MhC2fEBlanVgoe+aN9MsPjdhcvO1sKFVrP/i3IEpJT5GV4gII3bKsfSZZqN0VamaA+BqjMGW4FVn03/F+BZjIkaovEMLzRZrOOZ+aDAqxWUT8EDjOXCJXz0=
  - secure: Q09YHMSVdxmZY+Cjp1krd3c5Xwnje2rdW5rNW1gjdQD38s+JhO42L5ObR3pqHudc7lt8/l2EURDnAsE+1dTNkwqhsjaUMyDaDRdIGASWXKzlj29ZSgh/EB0fXLUKxXD6tDZeKZjNHuTIoE/2hdPRKT5rO/5luZ07HMNti5ujqsXYajuFSiQJZ0Ngb9ZqggAyftuQ/ROJBG/4ApTyS6FMCz6GxWvDcxVcwwbDuCa1ctDYvMWCInf+pCXj4mp+HrkiQbAzA3oWG35xC1TCN2aNRQBeSumo8uDKTJ4DNh4YEn/tRW+W/ifr7FYDb1UdmKoeEPS9w+GkEYOSjRblW0PXfc1JewRDzqJdhFPb7AdA/MRv2t2oAIg2U0pjqPBnULcruCYoS76vBxH+AdoFIFGxA/okHP5X7kWY1xaB5OHEzZoyDnF1eb3uEdA42BvPzP0pUHteX1jw0t+SQ512Brs6aX4kNJHyVR/oAs/asnQhD5bVKBTqNojAXhf7VsBx1fyLRiCvGoRAPjIyhll/dlk6BjUS61jN+rO6vrKgCLT6pTcIf64EKOfU77q0wp6uDQxIkIFMks3OwEn++mkS7bb6ETUG1UThdny6CCI9nSU9Jo6TNllylbYYA+nDvZ2J/s+89VhH0wQtkmIMoVocEd3pxLAwi6TACNQaonu3TNYlpSI=
