version: '3.6'
services:
    postgres:
        image: postgres
        container_name: "${PROJECT_NAME}_database"
        restart: always
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - ./data/postgres/initdb.d/:/docker-entrypoint-initdb.d/
            - ./data/postgres/data/db/:/usr/src/data/db/
    
    api:
        container_name: "${PROJECT_NAME}_backend"
        restart: always
        build:
            context: .
            dockerfile: ./packages/api/Dockerfile
        environment:
            - PORT=${API_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
        ports:
            - ${API_PORT}:${API_PORT}
        volumes:
            - ./:/usr/src/app
        links:
            - postgres
    
#    socket:
#        container_name: "${PROJECT_NAME}_socket"
#        restart: always
#        build:
#            context: .
#            dockerfile: ./packages/socket/Dockerfile
#        environment:
#            - PORT=${SOCKET_PORT}
#        ports:
#            - ${SOCKET_PORT}:${SOCKET_PORT}
#        volumes:
#            - ./:/usr/src/app
#        links:
#            - postgres
#            - api
        
    web:
        container_name: "${PROJECT_NAME}_web"
        build:
            context: .
            dockerfile: ./packages/web/Dockerfile
        ports:
            - ${WEBAPP_PORT}:${WEBAPP_PORT}
        volumes:
            - ./:/usr/src/app
        links:
            - api
#            - socket
        
    frontend:
        container_name: "${PROJECT_NAME}_frontend"
        build:
            context: .
            dockerfile: ./packages/frontend/Dockerfile
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        volumes:
            - ./:/usr/src/app
